
DROP DATABASE TT;
CREATE DATABASE TT;
USE TT

CREATE TABLE USERS(
    ID INT NOT NULL AUTO_INCREMENT,
    NICK VARCHAR(100),
    PASS VARCHAR(100),
    PRIMARY KEY (ID));

CREATE TABLE TIMETABLES(
    ID INT NOT NULL AUTO_INCREMENT,
    USER_ID INT,
    NAME VARCHAR(100),
    DAYS INT,
    INTERVALS INT,
    -- next 3 fields are expressed in minutes
    INTERVAL_START INT,
    INTERVAL_LENGTH INT,
    INTERVAL_GAP INT,
    DAY_NAMES VARCHAR(200),
    PRIMARY KEY (ID));

CREATE TABLE RESOURCES(
    ID INT NOT NULL AUTO_INCREMENT,
    TT_ID INT,
    -- PROF, CLASS or ROOM
    TYPE VARCHAR(10),
    NAME VARCHAR(100),
    AVL TEXT,
    -- if the resource is a CLASS, it may be in fact be
    -- a group of classes
    CONTAINS VARCHAR(100),
    SIZE INT,
    PRIMARY KEY (ID));

CREATE TABLE ACTIVITIES(
    ID INT NOT NULL AUTO_INCREMENT,
    TT_ID INT,
    CLASS_ID INT,
    PROF_ID INT,
    -- MANDATORY or DESIRABLE
    TYPE VARCHAR(10),
    LENGTH INT,
    PRIMARY KEY (ID));

CREATE TABLE SCHED_ACTIVITIES(
    ID INT NOT NULL AUTO_INCREMENT,
    TT_ID INT,
    CLASS_ID INT,
    PROF_ID INT,
    ROOM_ID INT,
    DAY INT,
    INT_NO INT,
    -- 0 - no tweak, 1 - don't regenerate, 2 - directly set by user
    TWEAK INT,
    PRIMARY KEY (ID));

-- test stuff
INSERT INTO USERS (NICK, PASS) VALUES ('Miron', '');
